Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2021-11, with the labels that each got.

#30 Update README.md about memory allocation to Docker
  README.md
Labels: kind/bug, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#39 Add sanposhiho to approvers
  OWNERS
Labels: sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#25 Set environment variable HOST=0.0.0.0 to simulator-frontend in docker-compse.yaml
  docker-compose.yml
Labels: kind/bug, sig/scheduling, lgtm, ok-to-test, size/XS, cncf-cla: yes, approved

#36 Updated restart scheduler for restore old setting
  scheduler/scheduler.go
Labels: sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#43 add pull request template
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: size/M, sig/scheduling, lgtm, cncf-cla: yes, approved

#45 pin node image to Node.js v16
  web/Dockerfile
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved
