Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2021-12, with the labels that each got.

#9 Fix: file name .dockerignore has blank
  .dockerignore
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#40 use https instead of ssh for submodule
  .gitmodules
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#21 Support build with cloudbuild for gcr
  cloudbuild.yaml
Labels: kind/feature, tide/merge-method-squash, size/M, sig/scheduling, lgtm, cncf-cla: yes, approved

#51 Move PULL_REQUEST_TEMPLATE.md to a valid place
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#54 add reset scheduler configuration
  docs/api.md
  scheduler/scheduler.go
  server/di/interface.go
  server/handler/schedulerconfig.go
  server/server.go
Labels: kind/feature, tide/merge-method-squash, size/M, sig/scheduling, lgtm, ok-to-test, cncf-cla: yes, approved, kind/api-change

#57 fix error message
  simulator.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#59 add prealloc linter and fix detected target
  .golangci.yml
  scheduler/plugin/plugins.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#50 Fix syntax error on cloudbuild.yaml
  cloudbuild.yaml
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#49 support PriorityClass on backend
  docs/api.md
  priorityclass/priorityclass.go
  server/di/di.go
  server/di/interface.go
  server/handler/priorityclass.go
  server/server.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L

#7 improve lint setting on frontend
  web/.eslintrc.js
  web/api/v1/index.ts
  web/api/v1/node.ts
  web/api/v1/pod.ts
  web/api/v1/pv.ts
  web/api/v1/pvc.ts
  web/api/v1/schedulerconfiguration.ts
  web/api/v1/storageclass.ts
  web/api/v1/types.ts
  web/components/NodeList.vue
  web/components/PVCList.vue
  web/components/PVList.vue
  web/components/PodList.vue
  web/components/ResourceAddButton.vue
  web/components/ResourceBar/BarHeader.vue
  web/components/ResourceBar/DefinitionTree.vue
  web/components/ResourceBar/DeleteButton.vue
  web/components/ResourceBar/ResourceBar.vue
  web/components/ResourceBar/SchedulingResults.vue
  web/components/ResourceBar/YamlEditor.vue
  web/components/SchedulerConfigurationEditButton.vue
  web/components/Snackbar.vue
  web/components/StorageClassList.vue
  web/components/StoreKey/NodeStoreKey.ts
  web/components/StoreKey/PVCStoreKey.ts
  web/components/StoreKey/PVStoreKey.ts
  web/components/StoreKey/PodStoreKey.ts
  web/components/StoreKey/SchedulerConfigurationStoreKey.ts
  web/components/StoreKey/SnackBarStoreKey.ts
  web/components/StoreKey/StorageClassStoreKey.ts
  web/components/StoreProvider/NodeStoreProvider.vue
  web/components/StoreProvider/PVCStoreProvider.vue
  web/components/StoreProvider/PVStoreProvider.vue
  web/components/StoreProvider/PodStoreProvider.vue
  web/components/StoreProvider/SchedulerConfigurationStoreProvider.vue
  web/components/StoreProvider/SnackbarStoreProvider.vue
  web/components/StoreProvider/StorageClassStoreProvider.vue
  web/components/UnscheduledPodList.vue
  web/components/lib/template.ts
  web/components/lib/templates/node.yaml
  web/components/lib/templates/pod.yaml
  web/components/lib/util.ts
  web/jest.config.js
  web/layouts/default.vue
  web/layouts/error.vue
  web/nuxt.config.js
  web/package.json
  web/pages/index.vue
  web/store/node.ts
  web/store/pod.ts
  web/store/pv.ts
  web/store/pvc.ts
  web/store/schedulerconfiguration.ts
  web/store/snackbar.ts
  web/store/storageclass.ts
  web/test/Logo.spec.js
  web/tsconfig.eslint.json
  web/yarn.lock
Labels: tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL

#63 Fix the lint issue on `NewSimulatorServer` with nolint directive
  server/server.go
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#62 change context for frontend build
  cloudbuild.yaml
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#65 extend timeout for cloud build
  cloudbuild.yaml
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#66 fix klog format
  k8sapiserver/k8sapiserver.go
  scheduler/scheduler.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#58 Feature add frontend ci
  .github/workflows/lint-frontend.yml
  web/package.json
Labels: kind/feature, tide/merge-method-squash, size/M, sig/scheduling, lgtm, cncf-cla: yes, approved

#53 support PriorityClass on frontend
  web/api/v1/node.ts
  web/api/v1/pod.ts
  web/api/v1/priorityclass.ts
  web/api/v1/pv.ts
  web/api/v1/pvc.ts
  web/api/v1/schedulerconfiguration.ts
  web/api/v1/storageclass.ts
  web/components/PriorityClassList.vue
  web/components/ResourceAddButton.vue
  web/components/ResourceBar/ResourceBar.vue
  web/components/StoreKey/PriorityClassStoreKey.ts
  web/components/StoreProvider/PriorityClassStoreProvider.vue
  web/components/lib/template.ts
  web/components/lib/templates/priorityclass.yaml
  web/nuxt.config.js
  web/pages/index.vue
  web/store/priorityclass.ts
Labels: tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L
