Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2022-05, with the labels that each got.

#157 Rename the environment variable FRONTEND_URL to CORS_ALLOWED_ORIGIN_LIST and accept list
  config/config.go
  config/config_test.go
  docker-compose.yml
  hack/start_simulator.sh
  k8sapiserver/k8sapiserver.go
  server/server.go
  simulator.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, kind/cleanup, lgtm, cncf-cla: yes, approved, size/L

#158 Cleanup deprecated handler
  docs/api.md
  server/handler/node.go
  server/handler/persistentvolume.go
  server/handler/persistentvolumeclaim.go
  server/handler/pod.go
  server/handler/priorityclass.go
  server/handler/storageclass.go
  server/server.go
Labels: tide/merge-method-squash, sig/scheduling, kind/cleanup, lgtm, cncf-cla: yes, approved, size/XXL

#162 Fixed how to specify the namespace in `Reset` function for resources with a namespace
  node/node.go
  node/node_test.go
  reset/reset.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L

#163 Fix error handling on calling of reset function on the web UI.
  web/components/TopBar/ResetButton.vue
Labels: kind/bug, tide/merge-method-squash, size/M, sig/scheduling, lgtm, cncf-cla: yes, approved

#169 fix: add docker-compose.yml to .dockerignore
  .dockerignore
Labels: tide/merge-method-squash, sig/scheduling, kind/cleanup, lgtm, size/XS, cncf-cla: yes, approved

#164 change the `Reset` API to be called directly
  web/components/StoreKey/ResetStoreKey.ts
  web/components/StoreProvider/ResetProvider.vue
  web/components/TopBar/ResetButton.vue
  web/pages/index.vue
  web/store/reset.ts
Labels: tide/merge-method-squash, size/M, sig/scheduling, kind/cleanup, lgtm, ok-to-test, cncf-cla: yes, approved

#153 [Frontend]Implement to `publicRuntimeConfig` for that BASE_URL and KUBE_API_SERVER_URL can be set in env for frontend image
  docker-compose.yml
  web/Dockerfile
  web/api/APIProvider.vue
  web/api/APIProviderKeys.ts
  web/api/v1/export.ts
  web/api/v1/index.ts
  web/api/v1/node.ts
  web/api/v1/pod.ts
  web/api/v1/priorityclass.ts
  web/api/v1/pv.ts
  web/api/v1/pvc.ts
  web/api/v1/reset.ts
  web/api/v1/schedulerconfiguration.ts
  web/api/v1/storageclass.ts
  web/components/TopBar/ExportButton.vue
  web/components/TopBar/ImportButton.vue
  web/components/TopBar/ResetButton.vue
  web/nuxt.config.js
  web/pages/index.vue
  web/plugins/ApiRuntimeConfigPlugin.ts
  web/plugins/README.md
  web/store/node.ts
  web/store/pod.ts
  web/store/priorityclass.ts
  web/store/pv.ts
  web/store/pvc.ts
  web/store/schedulerconfiguration.ts
  web/store/storageclass.ts
Labels: kind/bug, kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL

#174 Introduce internal kep to the project
  CONTRIBUTING.md
  keps/README.md
Labels: tide/merge-method-squash, size/M, sig/scheduling, lgtm, cncf-cla: yes, approved, kind/documentation

#168 [Frontend] Use GenerateName instead of Name in resource templates
  web/api/v1/node.ts
  web/api/v1/pod.ts
  web/api/v1/priorityclass.ts
  web/api/v1/pv.ts
  web/api/v1/pvc.ts
  web/api/v1/storageclass.ts
  web/components/ResourceAddButton.vue
  web/components/lib/template.ts
  web/components/lib/templates/node.yaml
  web/components/lib/templates/pod.yaml
  web/components/lib/templates/priorityclass.yaml
  web/components/lib/templates/pv.yaml
  web/components/lib/templates/pvc.yaml
  web/components/lib/templates/storageclass.yaml
  web/store/node.ts
  web/store/pod.ts
  web/store/priorityclass.ts
  web/store/pv.ts
  web/store/pvc.ts
  web/store/storageclass.ts
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#177 Support custom plugins in the simulator
  README.md
  config/config.go
  docs/how-to-use-custom-plugins/README.md
  docs/how-to-use-custom-plugins/nodenumber/plugin.go
  docs/how-to-use-custom-plugins/result.jpg
  export/export_test.go
  scheduler/config/config.go
  scheduler/config/plugin.go
  scheduler/defaultconfig/defaultconfig.go
  scheduler/plugin/plugins.go
  scheduler/plugin/plugins_test.go
  scheduler/scheduler.go
  scheduler/scheduler_test.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, size/XL, cncf-cla: yes, approved
