Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2022-01, with the labels that each got.

#76 Update makefile for go-mod downloads
  Makefile
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#78 Update README.md to reflect the addition of PriorityClass
  README.md
  docs/how-it-works.md
  docs/images/resources.png
  web/.eslintrc.js
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation

#13 override configuration correctly, even if passed PluginConfig has args data on PluginConfig.Args.Raw
  .golangci.yml
  scheduler/plugin/plugins.go
  scheduler/plugin/plugins_test.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L

#80 support initial scheduler configuration option via an environment variable
  config/config.go
  config/config_test.go
  scheduler/scheduler.go
  server/di/di.go
  simulator.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#18 Workaround: v-data-table cannot scroll when the bar cannot be scrolled vertically
  web/components/ResourceBar/ResourceBar.vue
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#83 add initial config description on README
  README.md
Labels: tide/merge-method-squash, sig/scheduling, lgtm, needs-ok-to-test, size/XS, cncf-cla: yes, approved, kind/documentation

#68 add resources "delete all" method in each service
  go.mod
  node/mock_node/node.go
  node/node.go
  node/node_test.go
  persistentvolume/persistentvolume.go
  persistentvolumeclaim/persistentvolumeclaim.go
  pod/pod.go
  pod/pod_test.go
  priorityclass/priorityclass.go
  server/di/interface.go
  storageclass/storageclass.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L

#86 Fix lint error of ResourceBar
  web/components/ResourceBar/ResourceBar.vue
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, needs-ok-to-test, size/XS, cncf-cla: yes, approved
