Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2022-08, with the labels that each got.

#165 Implement listwatchresources API on the simulator
  simulator/docs/api.md
  simulator/resourcewatcher/eventproxy.go
  simulator/resourcewatcher/eventproxy_test.go
  simulator/resourcewatcher/mock_eventproxy_test.go
  simulator/resourcewatcher/mock_resourcewatcher/lister.go
  simulator/resourcewatcher/mock_resourcewatcher/streamWriter.go
  simulator/resourcewatcher/mock_resourcewatcher/watchInterface.go
  simulator/resourcewatcher/resourcewatcher.go
  simulator/resourcewatcher/resourcewatcher_test.go
  simulator/resourcewatcher/streamwriter/mock_streamwriter/responseStream.go
  simulator/resourcewatcher/streamwriter/streamwriter.go
  simulator/resourcewatcher/streamwriter/streamwriter_test.go
  simulator/server/di/di.go
  simulator/server/di/interface.go
  simulator/server/handler/watcher.go
  simulator/server/server.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL

#213 fix(util): handle semaphore internally
  simulator/export/export.go
  simulator/export/export_test.go
  simulator/util/errGroupWithSemaphore.go
  simulator/util/semaphored_errgroup.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L

#217 support external IP in docker-compose.yaml
  README.md
  docker-compose.yml
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, size/XS, cncf-cla: yes, approved, kind/documentation
