Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2022-04, with the labels that each got.

#143 Remove package-lock.json
  web/package-lock.json
Labels: tide/merge-method-squash, sig/scheduling, kind/cleanup, lgtm, cncf-cla: yes, approved, size/XXL

#100 Delete GitHub Actions
  .github/workflows/lint-backend.yaml
  .github/workflows/lint-frontend.yml
  .github/workflows/test-backend.yaml
Labels: tide/merge-method-squash, sig/scheduling, kind/cleanup, lgtm, cncf-cla: yes, approved, size/L

#15 Enable to check if etcd is on path in start_simulator.sh
  hack/start_simulator.sh
Labels: tide/merge-method-squash, sig/scheduling, size/S, lgtm, cncf-cla: yes, approved

#146 add check if Node has Pods or not before deleting scheduled Pods on Node
  web/components/ResourceBar/ResourceBar.vue
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, size/S, lgtm, cncf-cla: yes, approved

#137 support namespace in each service
  export/export.go
  export/export_test.go
  export/mock_export/pod.go
  export/mock_export/pvc.go
  node/mock_node/node.go
  node/node.go
  node/node_test.go
  persistentvolumeclaim/persistentvolumeclaim.go
  persistentvolumeclaim/persistentvolumeclaim_test.go
  pod/pod.go
  pod/pod_test.go
  reset/reset.go
  server/di/di.go
  server/di/interface.go
  server/handler/persistentvolumeclaim.go
  server/handler/pod.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, cncf-cla: yes, approved, size/XXL
