Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2022-07, with the labels that each got.

#200 Update Makefile to add PHONY `openapi`
  simulator/Makefile
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, priority/important-soon, lgtm, size/XS, cncf-cla: yes, approved

#199 Rename module to sigs.k8s.io/kube-scheduler-simulator/simulator
  simulator/.golangci.yml
  simulator/config/config.go
  simulator/export/export.go
  simulator/export/export_test.go
  simulator/go.mod
  simulator/node/node_test.go
  simulator/replicateexistingcluster/mock_replicateexistingcluster/export.go
  simulator/replicateexistingcluster/replicateexistingcluster.go
  simulator/replicateexistingcluster/replicateexistingcluster_test.go
  simulator/scheduler/plugin/plugins.go
  simulator/scheduler/plugin/resultstore/store.go
  simulator/scheduler/plugin/resultstore/store_test.go
  simulator/scheduler/plugin/wrappedplugin.go
  simulator/scheduler/plugin/wrappedplugin_test.go
  simulator/scheduler/scheduler.go
  simulator/scheduler/scheduler_test.go
  simulator/server/di/di.go
  simulator/server/di/interface.go
  simulator/server/handler/export.go
  simulator/server/handler/reset.go
  simulator/server/handler/schedulerconfig.go
  simulator/server/server.go
  simulator/simulator.go
Labels: tide/merge-method-squash, size/M, sig/scheduling, kind/cleanup, lgtm, cncf-cla: yes, approved

#205 Add "Go v1.17 or more" as prerequisite for contributers and upgrade golangci-lint to v1.46.2 for that
  CONTRIBUTING.md
  simulator/.golangci.yml
  simulator/Makefile
  simulator/export/mock_export/node.go
  simulator/export/mock_export/pod.go
  simulator/export/mock_export/priorityClass.go
  simulator/export/mock_export/pv.go
  simulator/export/mock_export/pvc.go
  simulator/export/mock_export/scheduler.go
  simulator/export/mock_export/storageClassc.go
  simulator/node/mock_node/node.go
  simulator/replicateexistingcluster/mock_replicateexistingcluster/export.go
  simulator/scheduler/plugin/mock/framework.go
  simulator/scheduler/plugin/mock/wrappedplugin.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL, kind/documentation

#207 Add --build_flags=--mod=mod flag to handle vendor in mockgen reflect mode
  simulator/Makefile
  simulator/export/export.go
  simulator/export/mock_export/node.go
  simulator/export/mock_export/pod.go
  simulator/export/mock_export/priorityClass.go
  simulator/export/mock_export/pv.go
  simulator/export/mock_export/pvc.go
  simulator/export/mock_export/scheduler.go
  simulator/export/mock_export/storageClassc.go
  simulator/node/mock_node/node.go
  simulator/node/node.go
  simulator/replicateexistingcluster/mock_replicateexistingcluster/export.go
  simulator/replicateexistingcluster/replicateexistingcluster.go
  simulator/scheduler/plugin/mock/framework.go
  simulator/scheduler/plugin/mock/wrappedplugin.go
  simulator/scheduler/plugin/wrappedplugin.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/L

#208 Fix to case-insensitive file name collision error of mock
  simulator/export/export.go
  simulator/export/mock_export/priorityclass.go
  simulator/export/mock_export/storageclass.go
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved

#122 Add release guide
  RELEASE.md
Labels: tide/merge-method-squash, size/M, sig/scheduling, lgtm, cncf-cla: yes, approved, kind/documentation

#196 Initialize the scenario controller by kubebuilder
  scenario/.dockerignore
  scenario/.gitignore
  scenario/Dockerfile
  scenario/Makefile
  scenario/PROJECT
  scenario/README.md
  scenario/api/v1alpha1/groupversion_info.go
  scenario/api/v1alpha1/scenario_types.go
  scenario/api/v1alpha1/zz_generated.deepcopy.go
  scenario/config/crd/kustomization.yaml
  scenario/config/crd/kustomizeconfig.yaml
  scenario/config/crd/patches/cainjection_in_scenarios.yaml
  scenario/config/crd/patches/webhook_in_scenarios.yaml
  scenario/config/default/kustomization.yaml
  scenario/config/default/manager_auth_proxy_patch.yaml
  scenario/config/default/manager_config_patch.yaml
  scenario/config/manager/controller_manager_config.yaml
  scenario/config/manager/kustomization.yaml
  scenario/config/manager/manager.yaml
  scenario/config/prometheus/kustomization.yaml
  scenario/config/prometheus/monitor.yaml
  scenario/config/rbac/auth_proxy_client_clusterrole.yaml
  scenario/config/rbac/auth_proxy_role.yaml
  scenario/config/rbac/auth_proxy_role_binding.yaml
  scenario/config/rbac/auth_proxy_service.yaml
  scenario/config/rbac/kustomization.yaml
  scenario/config/rbac/leader_election_role.yaml
  scenario/config/rbac/leader_election_role_binding.yaml
  scenario/config/rbac/role_binding.yaml
  scenario/config/rbac/scenario_editor_role.yaml
  scenario/config/rbac/scenario_viewer_role.yaml
  scenario/config/rbac/service_account.yaml
  scenario/config/samples/simulation_v1alpha1_scenario.yaml
  scenario/controllers/scenario_controller.go
  scenario/controllers/suite_test.go
  scenario/go.mod
  scenario/go.sum
  scenario/hack/boilerplate.go.txt
  scenario/main.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL

#209 Add 196Ikuchil to reviewers
  OWNERS
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation
