Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2023-08, with the labels that each got.

#316 Bump etcd to v3.4.26
  docker-compose-local.yml
  docker-compose.yml
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, size/XS, cncf-cla: yes, approved, area/simulator

#307 Config: add new lint rule duplicated-imports
  simulator/.golangci.yml
  simulator/scheduler/storereflector/storereflector.go
Labels: tide/merge-method-squash, size/M, sig/scheduling, kind/cleanup, lgtm, cncf-cla: yes, approved, area/simulator

#319 add `make docker_down_local`
  Makefile
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved
