Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2023-04, with the labels that each got.

#282 BugFix: some wrappedPlugin returns non suit status
  simulator/scheduler/plugin/wrappedplugin.go
  simulator/scheduler/plugin/wrappedplugin_test.go
Labels: kind/bug, tide/merge-method-squash, size/M, sig/scheduling, lgtm, cncf-cla: yes, approved, area/simulator, priority/next-release

#281 fix: pass the configuration file from build-env
  simulator/Dockerfile
  simulator/config/config.go
  simulator/docs/environment-variables.md
  simulator/docs/simulator-server-config.md
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, size/S, lgtm, triage/accepted, cncf-cla: yes, approved, priority/next-release

#276 Support v1 KubeSchedulerConfiguration
  simulator/config/config.go
  simulator/config/config_test.go
  simulator/docs/api-samples/v1/export.md
  simulator/docs/api.md
  simulator/docs/how-to-use-custom-plugins/README.md
  simulator/export/export.go
  simulator/export/export_test.go
  simulator/export/mock_export/scheduler.go
  simulator/go.mod
  simulator/go.sum
  simulator/scheduler/config/config.go
  simulator/scheduler/config/plugin.go
  simulator/scheduler/config/plugin_test.go
  simulator/scheduler/extender/extender.go
  simulator/scheduler/extender/service.go
  simulator/scheduler/extender/service_test.go
  simulator/scheduler/plugin/plugins.go
  simulator/scheduler/plugin/plugins_test.go
  simulator/scheduler/plugin/wrappedplugin.go
  simulator/scheduler/scheduler.go
  simulator/scheduler/scheduler_test.go
  simulator/server/di/di.go
  simulator/server/di/interface.go
  simulator/server/handler/export.go
  simulator/server/handler/schedulerconfig.go
Labels: tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL, priority/next-release

#274 feature(simulator): store previous scheduling result as a result history
  simulator/scheduler/extender/mock_extender/resultstore.go
  simulator/scheduler/extender/resultstore/resultstore.go
  simulator/scheduler/extender/resultstore/resultstore_test.go
  simulator/scheduler/plugin/resultstore/store.go
  simulator/scheduler/plugin/resultstore/store_test.go
  simulator/scheduler/storereflector/annotation.go
  simulator/scheduler/storereflector/mock_storereflector/resultstore.go
  simulator/scheduler/storereflector/storereflector.go
  simulator/scheduler/storereflector/storereflector_test.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, size/XL, cncf-cla: yes, approved, priority/next-release

#283 extend cloudbuild timeout
  cloudbuild.yaml
Labels: tide/merge-method-squash, sig/scheduling, kind/cleanup, lgtm, size/XS, cncf-cla: yes, approved

#284 Fix broken links and missing details in README
  README.md
Labels: tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, size/XS, cncf-cla: yes, approved, kind/documentation, area/simulator

#288 implement the external scheduler integration
  simulator/.golangci.yml
  simulator/go.mod
  simulator/go.sum
  simulator/pkg/README.md
  simulator/pkg/externalscheduler/command.go
  simulator/pkg/externalscheduler/external_scheduler.go
  simulator/scheduler/config/plugin.go
  simulator/scheduler/config/plugin_test.go
  simulator/scheduler/extender/mock_extender/resultstore.go
  simulator/scheduler/plugin/mock/wrappedplugin.go
  simulator/scheduler/plugin/plugins.go
  simulator/scheduler/plugin/plugins_test.go
  simulator/scheduler/plugin/resultstore/store.go
  simulator/scheduler/plugin/resultstore/store_test.go
  simulator/scheduler/plugin/wrappedplugin.go
  simulator/scheduler/plugin/wrappedplugin_test.go
  simulator/scheduler/scheduler.go
  simulator/scheduler/scheduler_test.go
  simulator/scheduler/storereflector/mock_storereflector/resultstore.go
  simulator/scheduler/storereflector/storereflector.go
  simulator/util/decoder.go
  simulator/util/decoder_test.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, cncf-cla: yes, approved, size/XXL, priority/next-release

#287 add missing docs (external scheduler and plugin extender)
  README.md
  simulator/docs/custom-plugin.md
  simulator/docs/environment-variables.md
  simulator/docs/external-scheduler.md
  simulator/docs/how-it-works.md
  simulator/docs/how-to-use-custom-plugins/README.md
  simulator/docs/images/result-nodenumber.jpg
  simulator/docs/integrate-your-scheduler.md
  simulator/docs/kube-apiserver.md
  simulator/docs/kubeconfig.yaml
  simulator/docs/plugin-extender.md
  simulator/docs/sample/external-scheduler/kubeconfig.yaml
  simulator/docs/sample/external-scheduler/main.go
  simulator/docs/sample/external-scheduler/scheduler.yaml
  simulator/docs/sample/nodenumber/plugin.go
  simulator/docs/sample/plugin-extender/extender.go
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XL, cncf-cla: yes, approved, kind/documentation, area/simulator, priority/next-release

#292 fix(deps): modify wrong version on go.mod
  simulator/go.mod
Labels: kind/bug, tide/merge-method-squash, sig/scheduling, priority/important-soon, size/S, lgtm, cncf-cla: yes, approved, area/simulator

#297 remove adtac from OWNERS
  OWNERS
Labels: tide/merge-method-squash, sig/scheduling, size/S, kind/cleanup, lgtm, cncf-cla: yes, approved

#299 Add 196Ikuchil to approvers
  OWNERS
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation
