Repository kubernetes-sigs/kube-scheduler-simulator, pull requests merged in 2025-04, with the labels that each got.

#412 Update import-cluster-resources.md
  simulator/docs/import-cluster-resources.md
Labels: tide/merge-method-squash, sig/scheduling, lgtm, needs-ok-to-test, size/XS, cncf-cla: yes, approved

#405 feat: implement recorder and replayer
  README.md
  simulator/cmd/sched-recorder/recorder.go
  simulator/cmd/simulator/simulator.go
  simulator/config.yaml
  simulator/config/config.go
  simulator/config/v1alpha1/types.go
  simulator/docs/import-cluster-resources.md
  simulator/docs/record-and-replay-cluster-changes.md
  simulator/docs/simulator-server-config.md
  simulator/recorder/recorder.go
  simulator/recorder/recorder_test.go
  simulator/replayer/mock_resourceapplier/resourceapplier.go
  simulator/replayer/replayer.go
  simulator/replayer/replayer_test.go
  simulator/resourceapplier/resourceapplier.go
  simulator/server/di/di.go
  simulator/server/di/interface.go
Labels: kind/feature, tide/merge-method-squash, sig/scheduling, lgtm, ok-to-test, cncf-cla: yes, approved, size/XXL, area/simulator

#415 fix: update the mailing list address
  RELEASE.md
Labels: tide/merge-method-squash, sig/scheduling, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation
